### ISSUE TITLE
Incorrect type declaration causes crashes in read-multiline-string

### ISSUE THREAD

**Issue by m-lw** [smithzvk/pythonic-string-reader#1]
The type declaration at https://github.com/smithzvk/pythonic-string-reader/blob/c8cd347e862858aa5489ae6804e553f5b2959111/pythonic-string-reader.lisp#L37 is incorrect because `get-macro-character` can return a symbol (the ANSI spec says _function designator_: http://www.lispworks.com/documentation/HyperSpec/Body/26_glo_f.htm#function_designator).

I suggest deleting that declaration because the performance of funcall is unlikely to be crucial here.

**Comment by smithzvk** [comment]
Agreed, thanks for the report.
