### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by daewok** [smithzvk/pythonic-string-reader#2]
Is it possible to get a license added to this code? I'm trying to get approval to open source some code and I think having a library somewhere in the dependency tree without a license will give my university's technology licensing office serious heart palpitations.

**Comment by smithzvk** [comment]
Contacted original author to clarify original licensing terms.  I'm hoping this can be resolved... if not it will probably need to be rewritten to ensure an Open Source or Free license.  The message i sent:

> Yury,
> 
> Years ago I found your Common Lisp reader macro for Python style triple quoted string literals.  I'm not sure where I found it, but I took note that it was originally authored by you and gave credit in the readme, but I needed it for something and copied it into a Github repo where it has since been extended, found use by others, and was included in Quicklisp.  The repo is here https://github.com/smithzvk/pythonic-string-reader
> 
> As it stands I have no license listed for this software and it is starting to concern some of the users.  I would like to remedy this situation.  It was a long time ago and I don't remember where or how I found it or the existence of any license, but knowing me, I would have only rehosted the code if I believed that it was intended to be released under an open source license.  Could you please clarify the licensing terms of this code.  If I was incorrect about my assumption of an open source license, please let me know and I will remove the repository.  Also, let me know if you wish me to transfer ownership of the repo to your account.
> 
> If I have the wrong Yury Sulsky or was otherwise mistaken/misremembering, please let me know and I'm sorry to waste your time.
> 
> Thanks,
> Zach KS
>

**Comment by smithzvk** [comment]
The response:

> Hi Zach,
>
> It's really sweet of you to reach out about this! I do remember writing that during my common lisp phase :-).
> 
> In terms of license, it's just public domain and I'm happy that someone else found it useful.
> 
> Have a great day!

So, it is public domain.  I think it should probably be transferred to something more formal but also non-copyleft.  I'm going to put a 3-clause BSD on it unless there is objection.

**Comment by daewok** [comment]
Sounds great to me! Thanks for taking care of this so quickly.
